In [1]:
'Janet Gonzalez'

'Janet Gonzalez'

In [11]:
stre = 'hola JANET, SALUDOS A "TODOS"'

In [12]:
stre

'hola JANET, SALUDOS A "TODOS"'

In [13]:
type(stre)

str

In [14]:
print('comillas simples')

comillas simples


In [15]:
print("comillas simples")

comillas simples


In [16]:
print('janet "hola"')

janet "hola"


In [17]:
print(" este texto tiene \n una nueva linea")

 este texto tiene 
 una nueva linea


In [19]:
print("Este texto tiene \nuna nueva linea")

Este texto tiene 
una nueva linea


In [21]:
print("Este texto tiene \t una nueva linea")

Este texto tiene 	 una nueva linea


In [22]:
print(r'C:\Users\Janet\Documents')

C:\Users\Janet\Documents


In [23]:
print("""De esta manera
nos ahorramos a nun
pero no a \tuna que es para la tabulacio""")

De esta manera
nos ahorramos a nun
pero no a 	una que es para la tabulacio


In [26]:
variable = "Teoria sobre este tema donde salto de linea es con \nson dos lineas"

In [27]:
variable

'Teoria sobre este tema donde salto de linea es con \nson dos lineas'

In [28]:
print(variable)

Teoria sobre este tema donde salto de linea es con 
son dos lineas


In [29]:
variable + variable

'Teoria sobre este tema donde salto de linea es con \nson dos lineasTeoria sobre este tema donde salto de linea es con \nson dos lineas'

In [30]:
variable

'Teoria sobre este tema donde salto de linea es con \nson dos lineas'

In [31]:
print(variable + variable)

Teoria sobre este tema donde salto de linea es con 
son dos lineasTeoria sobre este tema donde salto de linea es con 
son dos lineas


In [35]:
primero = "primer parte"
segundo = " segunda parte"

In [36]:
print("fusion de " + primero + segundo)

fusion de primer parte segunda parte


In [3]:
profesor = "Janet González"

In [4]:
profesor[2]

'n'

In [5]:
profesor[8]

'n'

In [6]:
profesor[10]

'á'

In [7]:
profesor[-1]

'z'

In [8]:
profesor[-2]

'e'

In [9]:
profesor[2:10]

'net Gonz'

In [10]:
profesor[1:]

'anet González'

In [11]:
profesor[2:] + profesor[:2]

'net GonzálezJa'

In [12]:
len(profesor)

14

In [13]:
listas = [5,9,"Janet",-8,"estudiantes"]

In [14]:
print(lista)

NameError: name 'lista' is not defined

In [15]:
listas[0]

5

In [16]:
listas[-1]

'estudiantes'

In [17]:
listas[2]

'Janet'

In [18]:
primer_parte = [1,2,3,4]
segunda_parte = [5,6,7]

In [19]:
primer_parte + segunda_parte

[1, 2, 3, 4, 5, 6, 7]

In [20]:
segunda_parte + [8,9,10]

[5, 6, 7, 8, 9, 10]

In [21]:
numeros = [1,2,3,4,9,6,7,8,9]

In [22]:
numeros[4] = 5

In [23]:
numeros

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [24]:
numeros.append(10)

In [25]:
numeros

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [26]:
texto ='Hola'
texto

'Hola'

In [27]:
import numpy as np

In [28]:
lista = [1,2,3]
lista

[1, 2, 3]

In [29]:
array = np.array(lista)
array

array([1, 2, 3])

In [30]:
rango = np.arange(0,10)
rango

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
rango = np.arange(0,30,3)
rango

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [32]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [34]:
rango = np.arange(0,200,4)
rango

array([  0,   4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,
        52,  56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100,
       104, 108, 112, 116, 120, 124, 128, 132, 136, 140, 144, 148, 152,
       156, 160, 164, 168, 172, 176, 180, 184, 188, 192, 196])

In [35]:
np.random.randint(0,80)

15

In [36]:
import random

In [37]:
print(random.randint(3, 9))

4


In [38]:
print(random.randint(3, 9))

9


In [39]:
print(random.randint(3, 9))

7


In [40]:
np.random.randint(0,80,10)

array([ 1, 30, 55,  3, 58, 27, 42,  7, 15, 63])

In [41]:
np.random.randint(0,80)

4

In [42]:
np.random.randint(0,80)

9

In [43]:
np.random.randint(0,80)

15

In [44]:
np.random.randint(0,80,(2,5))

array([[25, 51,  3, 16, 56],
       [50, 50, 79, 54, 34]])

In [45]:
np.random.randint(0,80,(3,10))

array([[ 9, 55, 16, 46, 79,  0, 63,  2, 55, 77],
       [72, 38, 65, 78, 17, 37, 69,  7, 42, 59],
       [11, 55, 10, 14, 77, 62, 55, 53, 33, 13]])

In [46]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [47]:
array

array([1, 2, 3])

In [48]:
array = np.random.randint(0,80,10)

In [49]:
array

array([39, 60, 31, 14, 64, 24, 32, 40, 11, 23])

In [50]:
array.max()

64

In [51]:
array.min()

11

In [52]:
array.argmin()

8

In [54]:
array.argmax()


4

In [55]:
array

array([39, 60, 31, 14, 64, 24, 32, 40, 11, 23])

In [56]:
array.reshape(2,5)

array([[39, 60, 31, 14, 64],
       [24, 32, 40, 11, 23]])

In [57]:
array.reshape(5,2)

array([[39, 60],
       [31, 14],
       [64, 24],
       [32, 40],
       [11, 23]])

In [58]:
array = array.reshape(5,2)

In [59]:
array

array([[39, 60],
       [31, 14],
       [64, 24],
       [32, 40],
       [11, 23]])

In [60]:
array[0,0]

39

In [63]:
array>60

array([[False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False]])

In [67]:
filtro = array > 10
array [filtro]

array([39, 60, 31, 14, 64, 24, 32, 40, 11, 23])

 Pandas

In [70]:
import pandas as pd

In [71]:
datos = pd.read_csv('salarios.csv')

In [72]:
datos

nombre  salario  Edad
0  Antonio     1000    40
1    Maria      900    30
2    Pedro      800    20
3     Juan     1100    50
4      Eva     1000    42

In [74]:
seleccion = datos['salario']
seleccion

0    1000
1     900
2     800
3    1100
4    1000
Name: salario, dtype: int64

In [75]:
seleccion = datos[['nombre','salario']]

In [76]:
seleccion

nombre  salario
0  Antonio     1000
1    Maria      900
2    Pedro      800
3     Juan     1100
4      Eva     1000

In [77]:
datos

nombre  salario  Edad
0  Antonio     1000    40
1    Maria      900    30
2    Pedro      800    20
3     Juan     1100    50
4      Eva     1000    42

In [86]:
filtro = datos['Edad'] > 35
seleccion = datos[filtro]

In [87]:
seleccion

nombre  salario  Edad
0  Antonio     1000    40
3     Juan     1100    50
4      Eva     1000    42

In [88]:
datos.columns

Index(['nombre', 'salario', 'Edad'], dtype='object')

In [90]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   nombre   5 non-null      object
 1   salario  5 non-null      int64 
 2   Edad     5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes


In [92]:
datos.describe()

salario      Edad
count     5.000000   5.00000
mean    960.000000  36.40000
std     114.017543  11.61034
min     800.000000  20.00000
25%     900.000000  30.00000
50%    1000.000000  40.00000
75%    1000.000000  42.00000
max    1100.000000  50.00000

In [93]:
import numpy as np

In [95]:
datos = np.arange(0,9).reshape(3,3)
datos

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
dataframe = pd.DataFrame(data=datos, columns=['c1', 'c2', 'c3'])                                            

In [99]:
dataframe

c1  c2  c3
0   0   1   2
1   3   4   5
2   6   7   8

In [101]:
dataframe = pd.DataFrame(data=datos, columns=['c1','c2','c3'], index=['i1', 'i2', 'i3'])

In [102]:
dataframe

c1  c2  c3
i1   0   1   2
i2   3   4   5
i3   6   7   8

In [103]:
dataframe = pd.DataFrame(data=datos, columns=['c1','c2','c3'], index=['1', '2', '3'])

In [104]:
dataframe

c1  c2  c3
1   0   1   2
2   3   4   5
3   6   7   8

In [105]:
#Ejercicio

In [106]:
import numpy as np

In [108]:
import pandas as pd

In [113]:
valores = np.random.randint(0,500,(10,5))

In [117]:
columnas = ['c1', 'c2', 'c3', 'c4', 'c5']

In [123]:
datos = pd.DataFrame(data=valores, columns = columnas, index=['1', '2', '3','4','5','6', '7', '8', '9', '10'])

In [124]:
datos

c1   c2   c3   c4   c5
1   390  448  178  442  106
2   411  172   15  420  195
3   146  456  483  286  243
4   117  356  113   36  234
5   214   37    1  494  208
6   448  241  102  238  186
7   426  368  310  241  171
8   323  291  350  280   79
9     6  449  280  198  156
10  406   54  311  253   69

In [125]:
#PLOTLY

In [1]:
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go

In [2]:
valorex = np.random.randint(0,100,50)
valorey = np.random.randint(0,100,50)

In [3]:
datos = [go.Scatter(x=valorex, y=valorey, mode='markers')]

In [4]:
pyo.plot(datos, filename='scatter.html')

'scatter.html'

In [5]:
capa = go.Layout(title='Scatter plot', xaxis=dict(title='Valores x'), yaxis=dict(title='valores y'))

In [6]:
figura = go.Figure(data = datos, layout=capa)

In [7]:
pyo.plot(figura, filename='scatter.html')

'scatter.html'

In [13]:
datos = [go.Scatter(x=valorex, y=valorey, mode='markers', 
                    marker=dict(size=6, color='gold', symbol='diamond', line=dict(width=2)))]

In [14]:
capa = go.Layout(title='Scatter plot', xaxis=dict(title='Valores x'), yaxis=dict(title='valores y'))

In [15]:
figura = go.Figure(data = datos, layout=capa)

In [16]:
pyo.plot(figura, filename='scatter.html')

'scatter.html'

In [17]:
#Gráfico tipo lineal 

In [25]:
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go

In [26]:
valoresx = np.linspace(0,1,50)

In [27]:
valoresx

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [28]:
valoresy = np.random.randn(50)
valoresy

array([-1.30197997, -0.25326315,  1.11681206, -0.32669954,  0.96869274,
        1.42225373,  1.12934313,  0.75026851, -0.60156602,  0.32143301,
        0.2181658 , -0.18864183,  0.95072773,  1.49325539, -0.63337903,
        0.13514719, -0.24060324,  2.12736659,  0.02051392, -0.56315376,
       -1.3649352 ,  0.33003724, -1.04495343, -0.55032584, -0.11303746,
        1.17282673,  1.19711004, -0.15319602, -0.97425416,  1.28365268,
       -0.7723179 ,  1.99857183,  1.01740547,  1.678172  , -0.86263034,
       -0.03339192, -0.20849097,  0.29999792, -1.27988074, -0.33052297,
        1.09064736, -0.4678237 ,  0.94139942,  0.58094085,  1.93581185,
       -0.1449584 ,  1.77972278,  0.97027967, -0.64601267, -0.30925622])

In [30]:
valores = go.Scatter(x=valoresx, y=valoresy, mode='lines')

In [31]:
datos = [valores]

In [32]:
capa = go.Layout(title='Grafico de tipo lineal')
figura = go.Figure(data=datos, layout=capa)
pyo.plot(figura)

'temp-plot.html'

In [3]:
# Plotly - Gráfico de barras